# This template is a reusable set of steps that can be shared by multiple CI pipelines.
#
# Documentation for this file format is here:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

steps:
  - script: 'git config --local user.email dpreleasebot@hbo.com'
    displayName: 'git config email'
  - script: 'git config --local user.name hbo-github-bot'
    displayName: 'git config name'
  - script: 'npm install'
    displayName: 'Install: parse-slash-command-action'
  - script: 'npm test'
    displayName: 'Test: parse-slash-command-action'
